import { z } from 'zod'
import { formatISO } from 'date-fns'
import { config } from '@/lib/config'
import type {
  SocialProvider,
  OAuthAuthorizeInput,
  ExchangeCodeInput,
  TokenSet,
  PublishInput,
  PublishResult,
  FetchMetricsInput,
  PostMetrics,
  FetchEngagementInput,
  EngagementItem,
  RefreshAccessTokenInput,
  RevokeAccessTokenInput,
} from './types'
import { SocialProviderError } from './errors'
import { withFreshToken } from './vault'
import { LINKEDIN_VERSION } from './constants'

// ADR 0028 §3.1/§5.1 (N2.7). Endpoints per N2.1's vendor-doc verification
// (docs/reviews/session-30-5-platform-verification.md items 1, 9) except
// the userinfo identity endpoint, verified separately in this step against
// Microsoft Learn's "Sign In with LinkedIn using OpenID Connect" doc
// (discovery document at https://www.linkedin.com/oauth/.well-known/
// openid-configuration, read 2026-09-04).
const LINKEDIN_AUTHORIZE_URL = 'https://www.linkedin.com/oauth/v2/authorization'
const LINKEDIN_TOKEN_URL = 'https://www.linkedin.com/oauth/v2/accessToken'
const LINKEDIN_USERINFO_URL = 'https://api.linkedin.com/v2/userinfo'
const LINKEDIN_POSTS_URL = 'https://api.linkedin.com/rest/posts'

const LinkedInTokenResponseSchema = z.object({
  access_token: z.string(),
  expires_in: z.number(),
  scope: z.string().optional(),
})

// The discovery document declares subject_types_supported: ["pairwise"] —
// `sub` may be an app-scoped pseudonymous identifier rather than the same
// id space LinkedIn's Posts/Marketing APIs use elsewhere for urn:li:person
// construction. This is the standard, documented third-party pattern
// (urn:li:person:{sub}) and matches ADR 0028 §5.1's design, but the
// pairwise-vs-shared-id-space question was NOT part of N2.1's verified
// list and is flagged here, not resolved — worth an empirical check once
// real LinkedIn credentials exist (ADR 0028 §14.1).
const LinkedInUserinfoSchema = z.object({
  sub: z.string(),
  name: z.string().optional(),
})

// ADR 0028 §5.1 — the URN is self-describing; no platform_account_type
// discriminator column is needed. This is the derived helper that reads
// the type from the prefix, closing that loser explicitly rather than by
// omission.
export function isOrganizationAuthorUrn(urn: string): boolean {
  return urn.startsWith('urn:li:organization:')
}

function buildCommentary(content: string, hashtags: readonly string[]): string {
  if (hashtags.length === 0) return content
  const tags = hashtags.map((h) => (h.startsWith('#') ? h : `#${h}`)).join(' ')
  return `${content}\n\n${tags}`
}

export class LinkedInProvider implements SocialProvider {
  readonly platform = 'linkedin' as const

  // The state param is a pre-signed JWT generated by the calling Server
  // Action via signOAuthState(). No PKCE — N2.1 confirmed LinkedIn's
  // standard confidential-client (server redirect_uri) flow neither
  // requires nor offers it without a LinkedIn-side enablement SOSH does
  // not have.
  async getOAuthAuthorizeUrl(input: OAuthAuthorizeInput): Promise<string> {
    const params = new URLSearchParams({
      response_type: 'code',
      client_id: config.server.LINKEDIN_CLIENT_ID,
      redirect_uri: input.redirectUri,
      state: input.state,
      scope: input.scopes.join(' '),
    })
    return `${LINKEDIN_AUTHORIZE_URL}?${params}`
  }

  async exchangeOAuthCode(input: ExchangeCodeInput): Promise<TokenSet> {
    let resp: Response
    try {
      resp = await fetch(LINKEDIN_TOKEN_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        // N2.1 finding 4: LinkedIn authenticates via client_id + client_secret
        // IN THE BODY, never HTTP Basic.
        body: new URLSearchParams({
          grant_type: 'authorization_code',
          code: input.code,
          redirect_uri: input.redirectUri,
          client_id: config.server.LINKEDIN_CLIENT_ID,
          client_secret: config.server.LINKEDIN_CLIENT_SECRET,
        }),
      })
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'exchangeOAuthCode: network error',
        platform: 'linkedin',
        details: { cause: String(err) },
      })
    }

    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `exchangeOAuthCode: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
        details: { platform_message: body },
      })
    }

    const rawBody = await resp.json()
    let parsed: z.infer<typeof LinkedInTokenResponseSchema>
    try {
      parsed = LinkedInTokenResponseSchema.parse(rawBody)
    } catch (e) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'LinkedIn returned an unexpected token response shape',
        platform: 'linkedin',
        details: { zodError: e instanceof Error ? e.message : String(e) },
      })
    }

    // Identity is a SECOND call — neither token response carries it (ADR §2.7).
    const identity = await this.fetchIdentity(parsed.access_token)

    return {
      accessToken: parsed.access_token,
      refreshToken: null, // supportsRefreshToken: false (ADR §4.3)
      tokenExpiresAt: formatISO(new Date(Date.now() + parsed.expires_in * 1000)),
      scopesGranted: parsed.scope ? parsed.scope.split(' ') : [],
      platformUserId: `urn:li:person:${identity.sub}`,
      platformUsername: identity.sub,
      platformDisplayName: identity.name ?? null,
    }
  }

  private async fetchIdentity(accessToken: string): Promise<z.infer<typeof LinkedInUserinfoSchema>> {
    let resp: Response
    try {
      resp = await fetch(LINKEDIN_USERINFO_URL, {
        headers: { Authorization: `Bearer ${accessToken}` },
      })
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'fetchIdentity: network error',
        platform: 'linkedin',
        details: { cause: String(err) },
      })
    }

    if (!resp.ok) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `fetchIdentity: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
      })
    }

    const rawBody = await resp.json()
    try {
      return LinkedInUserinfoSchema.parse(rawBody)
    } catch (e) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'LinkedIn returned an unexpected userinfo response shape',
        platform: 'linkedin',
        details: { zodError: e instanceof Error ? e.message : String(e) },
      })
    }
  }

  async publish(input: PublishInput): Promise<PublishResult> {
    // MEDIA GUARD (A-3, ADR §3.4) — before ANY network call, including
    // token resolution. Publishing text-only and dropping the media is
    // the worst available failure for a human-in-the-loop product.
    if (input.mediaUrls.length > 0) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'publish: LinkedIn media publishing is deferred (30.5-MEDIA-UPLOAD)',
        platform: 'linkedin',
        details: { reason: 'media_deferred', mediaCount: input.mediaUrls.length },
      })
    }

    return withFreshToken(
      input.socialAccountId,
      (id) => this.refreshAccessToken({ socialAccountId: id }),
      async (token) => {
        const { createServiceRoleClient } = await import('@/lib/supabase/service')
        const client = createServiceRoleClient()
        const { data: account, error } = await client
          .from('social_accounts')
          .select('platform_user_id')
          .eq('id', input.socialAccountId)
          .single()

        if (error || !account) {
          throw new SocialProviderError({
            code: 'TOKEN_REVOKED',
            message: `publish: social account ${input.socialAccountId} not found`,
            platform: 'linkedin',
          })
        }

        // SOCIAL-LI-AUTHOR-URN: person and organization URNs both flow
        // through this SAME code path unmodified — the scope to actually
        // request as an organization is deferred (A-8), the plumbing is not.
        const authorUrn = account.platform_user_id as string

        let resp: Response
        try {
          resp = await fetch(LINKEDIN_POSTS_URL, {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${token}`,
              'Linkedin-Version': LINKEDIN_VERSION,
              'X-Restli-Protocol-Version': '2.0.0',
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              author: authorUrn,
              commentary: buildCommentary(input.content, input.hashtags),
              visibility: 'PUBLIC',
              distribution: {
                feedDistribution: 'MAIN_FEED',
                targetEntities: [],
                thirdPartyDistributionChannels: [],
              },
              lifecycleState: 'PUBLISHED',
              isReshareDisabledByAuthor: false,
            }),
          })
        } catch (err) {
          throw new SocialProviderError({
            code: 'NETWORK',
            message: 'publish: network error',
            platform: 'linkedin',
            details: { cause: String(err) },
          })
        }

        return this.handlePublishResponse(resp)
      },
    )
  }

  private async handlePublishResponse(resp: Response): Promise<PublishResult> {
    if (resp.status === 429) {
      const retryAfter = Number(resp.headers.get('Retry-After') ?? '60')
      throw new SocialProviderError({
        code: 'RATE_LIMITED',
        message: 'publish: rate limited by LinkedIn',
        platform: 'linkedin',
        retryAfterSeconds: Number.isFinite(retryAfter) ? retryAfter : 60,
      })
    }

    if (resp.status === 401 || resp.status === 403) {
      throw new SocialProviderError({
        code: 'TOKEN_EXPIRED',
        message: `publish: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
      })
    }

    if (resp.status !== 201) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: resp.status >= 500 ? 'NETWORK' : 'PLATFORM_REJECTED',
        message: `publish: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
        details: { platform_message: body },
      })
    }

    // SOCIAL-LI-POSTID-FROM-HEADER: the created post id arrives in the
    // x-restli-id response HEADER on a 201, never the body — ADR 0028 calls
    // this "the single most likely native-implementation mistake". The
    // body is never even read on this path, so a decoy id in the body
    // cannot leak through.
    const postUrn = resp.headers.get('x-restli-id')
    if (!postUrn) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'publish: LinkedIn 201 response missing x-restli-id header',
        platform: 'linkedin',
      })
    }

    return {
      platformPostId: postUrn,
      publishedAt: formatISO(new Date()),
      url: `https://www.linkedin.com/feed/update/${postUrn}/`,
    }
  }

  async fetchPostMetrics(_input: FetchMetricsInput): Promise<PostMetrics | null> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'LinkedInProvider.fetchPostMetrics is not implemented yet',
      platform: 'linkedin',
      details: { method: 'fetchPostMetrics' },
    })
  }

  async fetchEngagement(_input: FetchEngagementInput): Promise<EngagementItem[]> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'LinkedInProvider.fetchEngagement is not implemented yet',
      platform: 'linkedin',
      details: { method: 'fetchEngagement' },
    })
  }

  // SOCIAL-LI-EXPIRY-REVOKED (ADR 0028 §4.3): LinkedIn access tokens
  // CANNOT be refreshed. TOKEN_REVOKED, never TOKEN_EXPIRED — the latter
  // triggers an in-tick refresh-and-retry (ADR 0005 §5) that can never
  // succeed for LinkedIn, burning the tick's refresh budget and producing
  // reason: 'refresh_loop'. TOKEN_REVOKED marks the post failed with the
  // truthful "Reconnect account" signal, which is the terminal branch.
  async refreshAccessToken(_input: RefreshAccessTokenInput): Promise<TokenSet> {
    throw new SocialProviderError({
      code: 'TOKEN_REVOKED',
      message: 'refreshAccessToken: LinkedIn access tokens cannot be refreshed — reconnection required',
      platform: 'linkedin',
    })
  }

  // SOCIAL-REVOKE-NEVER-BLOCKS: N2.1 (finding 3) confirmed LinkedIn has no
  // programmatic revocation endpoint for a standard third-party app —
  // revocation is member-initiated only, through the member's own LinkedIn
  // account settings. Best-effort here means "nothing to call", not
  // "swallow a network failure": there is genuinely no request to attempt,
  // so this never throws and never blocks local deactivation or
  // purge_business.
  async revokeAccessToken(_input: RevokeAccessTokenInput): Promise<void> {
    return
  }
}
