import { z } from 'zod'
import { formatISO } from 'date-fns'
import { config } from '@/lib/config'
import { toUtcIso } from '@/lib/utils'
import type {
  SocialProvider,
  OAuthAuthorizeInput,
  ExchangeCodeInput,
  TokenSet,
  PublishInput,
  PublishResult,
  FetchMetricsInput,
  PostMetrics,
  FetchEngagementInput,
  EngagementItem,
  RefreshAccessTokenInput,
  RevokeAccessTokenInput,
} from './types'
import { SocialProviderError } from './errors'
import { withFreshToken } from './vault'
import {
  LINKEDIN_VERSION,
  assertRecentPostsPageSize,
  RECENT_POST_CONTENT_MAX_CHARS,
  SOCIAL_READ_TIMEOUT_MS,
} from './constants'
import { mapHttpStatusToErrorCode, finiteRetryAfterSeconds } from './error-mapping'
import type { FetchRecentPostsInput, RecentPostsPage, RecentPost } from './types'

// ADR 0028 §3.1/§5.1 (N2.7). LINKEDIN_AUTHORIZE_URL/LINKEDIN_TOKEN_URL are
// sourced by N2.1 item 1 (docs/reviews/session-30-5-platform-verification.md).
// LINKEDIN_POSTS_URL was corrected in Session 30.5-D (BLOCKER-1): item 1
// covers only the authorize/token URLs and item 9 covers the Linkedin-Version
// header value — neither contains the Posts API base URL. Now sourced in
// the same file's Appendix A (item 12, read 2026-09-05, Microsoft Learn).
const LINKEDIN_AUTHORIZE_URL = 'https://www.linkedin.com/oauth/v2/authorization'
const LINKEDIN_TOKEN_URL = 'https://www.linkedin.com/oauth/v2/accessToken'
// LINKEDIN_USERINFO_URL: sourced in Appendix A item 13 (read 2026-09-05) —
// moved out of a code-comment-only citation per MINOR-1. The OIDC discovery
// document's subject_types_supported is ["pairwise"] (confirmed verbatim);
// see ADR 0028 §16 item 9 for the open question this raises about whether
// `sub` matches the urn:li:person: id space constructed elsewhere.
const LINKEDIN_USERINFO_URL = 'https://api.linkedin.com/v2/userinfo'
const LINKEDIN_POSTS_URL = 'https://api.linkedin.com/rest/posts'

const LinkedInTokenResponseSchema = z.object({
  access_token: z.string(),
  expires_in: z.number(),
  scope: z.string().optional(),
})

// The discovery document declares subject_types_supported: ["pairwise"] —
// `sub` may be an app-scoped pseudonymous identifier rather than the same
// id space LinkedIn's Posts/Marketing APIs use elsewhere for urn:li:person
// construction. This is the standard, documented third-party pattern
// (urn:li:person:{sub}) and matches ADR 0028 §5.1's design, but the
// pairwise-vs-shared-id-space question was NOT part of N2.1's verified
// list and is flagged here, not resolved — worth an empirical check once
// real LinkedIn credentials exist (ADR 0028 §14.1).
const LinkedInUserinfoSchema = z.object({
  sub: z.string(),
  name: z.string().optional(),
})

// UNVERIFIED against the live API — ADR 0025 A-1. Best-effort shape for the
// Posts API author-finder response; never exercised (see fetchRecentPostsBody).
const LinkedInPostsListSchema = z.object({
  elements: z
    .array(
      z.object({
        id: z.string(),
        // LinkedIn's REST APIs conventionally return createdAt as epoch
        // millis (a number), not an ISO string — normalized here so the
        // caller's `new Date(...)` parse always sees a valid ISO string.
        createdAt: z.union([z.string(), z.number()]).transform((v) => (typeof v === 'number' ? toUtcIso(new Date(v)) : v)),
        commentary: z.string().optional(),
        reshareContext: z.unknown().optional(),
        content: z
          .object({
            media: z.unknown().optional(),
            article: z.unknown().optional(),
          })
          .optional(),
      }),
    )
    .optional(),
  paging: z.object({ start: z.number().optional(), count: z.number().optional(), total: z.number().optional() }).optional(),
})

// ADR 0028 §5.1 — the URN is self-describing; no platform_account_type
// discriminator column is needed. This is the derived helper that reads
// the type from the prefix, closing that loser explicitly rather than by
// omission.
export function isOrganizationAuthorUrn(urn: string): boolean {
  return urn.startsWith('urn:li:organization:')
}

function buildCommentary(content: string, hashtags: readonly string[]): string {
  if (hashtags.length === 0) return content
  const tags = hashtags.map((h) => (h.startsWith('#') ? h : `#${h}`)).join(' ')
  return `${content}\n\n${tags}`
}

export class LinkedInProvider implements SocialProvider {
  readonly platform = 'linkedin' as const
  // ADR 0025 §2.7/A-1: built against LinkedIn's docs, UNVERIFIED, NOT
  // SERVED. Unlike TwitterProvider's stub, this stays false beyond I2.2 —
  // Amendment B §B.5 forbids implementing the real body this session.
  readonly historicalReadAvailable = false

  // The state param is a pre-signed JWT generated by the calling Server
  // Action via signOAuthState(). No PKCE — N2.1 confirmed LinkedIn's
  // standard confidential-client (server redirect_uri) flow neither
  // requires nor offers it without a LinkedIn-side enablement SOSH does
  // not have.
  async getOAuthAuthorizeUrl(input: OAuthAuthorizeInput): Promise<string> {
    const params = new URLSearchParams({
      response_type: 'code',
      client_id: config.server.LINKEDIN_CLIENT_ID,
      redirect_uri: input.redirectUri,
      state: input.state,
      scope: input.scopes.join(' '),
    })
    return `${LINKEDIN_AUTHORIZE_URL}?${params}`
  }

  async exchangeOAuthCode(input: ExchangeCodeInput): Promise<TokenSet> {
    let resp: Response
    try {
      resp = await fetch(LINKEDIN_TOKEN_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        // N2.1 finding 4: LinkedIn authenticates via client_id + client_secret
        // IN THE BODY, never HTTP Basic.
        body: new URLSearchParams({
          grant_type: 'authorization_code',
          code: input.code,
          redirect_uri: input.redirectUri,
          client_id: config.server.LINKEDIN_CLIENT_ID,
          client_secret: config.server.LINKEDIN_CLIENT_SECRET,
        }),
      })
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'exchangeOAuthCode: network error',
        platform: 'linkedin',
        details: { cause: String(err) },
      })
    }

    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `exchangeOAuthCode: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
        details: { platform_message: body },
      })
    }

    const rawBody = await resp.json()
    let parsed: z.infer<typeof LinkedInTokenResponseSchema>
    try {
      parsed = LinkedInTokenResponseSchema.parse(rawBody)
    } catch (e) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'LinkedIn returned an unexpected token response shape',
        platform: 'linkedin',
        details: { zodError: e instanceof Error ? e.message : String(e) },
      })
    }

    // Identity is a SECOND call — neither token response carries it (ADR §2.7).
    const identity = await this.fetchIdentity(parsed.access_token)

    return {
      accessToken: parsed.access_token,
      refreshToken: null, // supportsRefreshToken: false (ADR §4.3)
      tokenExpiresAt: formatISO(new Date(Date.now() + parsed.expires_in * 1000)),
      scopesGranted: parsed.scope ? parsed.scope.split(' ') : [],
      platformUserId: `urn:li:person:${identity.sub}`,
      platformUsername: identity.sub,
      platformDisplayName: identity.name ?? null,
    }
  }

  private async fetchIdentity(accessToken: string): Promise<z.infer<typeof LinkedInUserinfoSchema>> {
    let resp: Response
    try {
      resp = await fetch(LINKEDIN_USERINFO_URL, {
        headers: { Authorization: `Bearer ${accessToken}` },
      })
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'fetchIdentity: network error',
        platform: 'linkedin',
        details: { cause: String(err) },
      })
    }

    if (!resp.ok) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `fetchIdentity: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
      })
    }

    const rawBody = await resp.json()
    try {
      return LinkedInUserinfoSchema.parse(rawBody)
    } catch (e) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'LinkedIn returned an unexpected userinfo response shape',
        platform: 'linkedin',
        details: { zodError: e instanceof Error ? e.message : String(e) },
      })
    }
  }

  async publish(input: PublishInput): Promise<PublishResult> {
    // MEDIA GUARD (A-3, ADR §3.4) — before ANY network call, including
    // token resolution. Publishing text-only and dropping the media is
    // the worst available failure for a human-in-the-loop product.
    if (input.mediaUrls.length > 0) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'publish: LinkedIn media publishing is deferred (30.5-MEDIA-UPLOAD)',
        platform: 'linkedin',
        details: { reason: 'media_deferred', mediaCount: input.mediaUrls.length },
      })
    }

    return withFreshToken(
      input.socialAccountId,
      (id) => this.refreshAccessToken({ socialAccountId: id }),
      async (token) => {
        const { createServiceRoleClient } = await import('@/lib/supabase/service')
        const client = createServiceRoleClient()
        const { data: account, error } = await client
          .from('social_accounts')
          .select('platform_user_id')
          .eq('id', input.socialAccountId)
          .single()

        if (error || !account) {
          throw new SocialProviderError({
            code: 'TOKEN_REVOKED',
            message: `publish: social account ${input.socialAccountId} not found`,
            platform: 'linkedin',
          })
        }

        // SOCIAL-LI-AUTHOR-URN: person and organization URNs both flow
        // through this SAME code path unmodified — the scope to actually
        // request as an organization is deferred (A-8), the plumbing is not.
        const authorUrn = account.platform_user_id as string

        let resp: Response
        try {
          resp = await fetch(LINKEDIN_POSTS_URL, {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${token}`,
              'Linkedin-Version': LINKEDIN_VERSION,
              'X-Restli-Protocol-Version': '2.0.0',
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              author: authorUrn,
              commentary: buildCommentary(input.content, input.hashtags),
              visibility: 'PUBLIC',
              distribution: {
                feedDistribution: 'MAIN_FEED',
                targetEntities: [],
                thirdPartyDistributionChannels: [],
              },
              lifecycleState: 'PUBLISHED',
              isReshareDisabledByAuthor: false,
            }),
          })
        } catch (err) {
          throw new SocialProviderError({
            code: 'NETWORK',
            message: 'publish: network error',
            platform: 'linkedin',
            details: { cause: String(err) },
          })
        }

        return this.handlePublishResponse(resp)
      },
    )
  }

  private async handlePublishResponse(resp: Response): Promise<PublishResult> {
    if (resp.status === 429) {
      const retryAfter = Number(resp.headers.get('Retry-After') ?? '60')
      throw new SocialProviderError({
        code: 'RATE_LIMITED',
        message: 'publish: rate limited by LinkedIn',
        platform: 'linkedin',
        retryAfterSeconds: finiteRetryAfterSeconds(retryAfter),
      })
    }

    if (resp.status !== 201) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: mapHttpStatusToErrorCode(resp.status),
        message: `publish: LinkedIn returned ${resp.status}`,
        platform: 'linkedin',
        details: { platform_message: body },
      })
    }

    // SOCIAL-LI-POSTID-FROM-HEADER: the created post id arrives in the
    // x-restli-id response HEADER on a 201, never the body — ADR 0028 calls
    // this "the single most likely native-implementation mistake". The
    // body is never even read on this path, so a decoy id in the body
    // cannot leak through.
    const postUrn = resp.headers.get('x-restli-id')
    if (!postUrn) {
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: 'publish: LinkedIn 201 response missing x-restli-id header',
        platform: 'linkedin',
      })
    }

    return {
      platformPostId: postUrn,
      publishedAt: formatISO(new Date()),
      url: `https://www.linkedin.com/feed/update/${postUrn}/`,
    }
  }

  // ADR 0026 §3.1 / ADR 0028 Amendment A (J2.1) — VERIFIED, then deliberately
  // left unimplemented. Reading like/comment counts (GET /rest/socialActions/
  // {urn} or /rest/socialMetadata/{urn}) needs r_member_social_feed, which
  // LinkedIn marks "Restricted … granted to select developers only"
  // (learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/
  // network-update-social-actions, read 2026-09-19). platforms/config.ts
  // grants only openid, profile, email, w_member_social, and adding a scope
  // forces every connected account to re-authorise (ADR 0028 §14.1). So this
  // keeps throwing NOT_IMPLEMENTED — which the metrics orchestrator already
  // short-circuits per platform — and the outcome loop runs on X alone.
  async fetchPostMetrics(_input: FetchMetricsInput): Promise<PostMetrics | null> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'LinkedInProvider.fetchPostMetrics is not implemented yet',
      platform: 'linkedin',
      details: { method: 'fetchPostMetrics', reason: 'r_member_social_feed_restricted' },
    })
  }

  async fetchEngagement(_input: FetchEngagementInput): Promise<EngagementItem[]> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'LinkedInProvider.fetchEngagement is not implemented yet',
      platform: 'linkedin',
      details: { method: 'fetchEngagement' },
    })
  }

  // SOCIAL-LI-EXPIRY-REVOKED (ADR 0028 §4.3): LinkedIn access tokens
  // CANNOT be refreshed. TOKEN_REVOKED, never TOKEN_EXPIRED — the latter
  // triggers an in-tick refresh-and-retry (ADR 0005 §5) that can never
  // succeed for LinkedIn, burning the tick's refresh budget and producing
  // reason: 'refresh_loop'. TOKEN_REVOKED marks the post failed with the
  // truthful "Reconnect account" signal, which is the terminal branch.
  async refreshAccessToken(_input: RefreshAccessTokenInput): Promise<TokenSet> {
    throw new SocialProviderError({
      code: 'TOKEN_REVOKED',
      message: 'refreshAccessToken: LinkedIn access tokens cannot be refreshed — reconnection required',
      platform: 'linkedin',
    })
  }

  // SOCIAL-REVOKE-NEVER-BLOCKS: N2.1 (finding 3) confirmed LinkedIn has no
  // programmatic revocation endpoint for a standard third-party app —
  // revocation is member-initiated only, through the member's own LinkedIn
  // account settings. Best-effort here means "nothing to call", not
  // "swallow a network failure": there is genuinely no request to attempt,
  // so this never throws and never blocks local deactivation or
  // purge_business.
  async revokeAccessToken(_input: RevokeAccessTokenInput): Promise<void> {
    return
  }

  // Amendment B §B.5 — NOT SERVED. Page size is still validated first
  // (RangeError before any I/O, on every implementation alike); the flag
  // check below then ALWAYS throws NOT_IMPLEMENTED with zero fetch calls —
  // historicalReadAvailable is a readonly `false`, so fetchRecentPostsBody
  // is structurally unreachable today, never executed, never tested.
  async fetchRecentPosts(input: FetchRecentPostsInput): Promise<RecentPostsPage> {
    assertRecentPostsPageSize(input.pageSize)
    if (!this.historicalReadAvailable) {
      throw new SocialProviderError({
        code: 'NOT_IMPLEMENTED',
        message: 'LinkedInProvider.fetchRecentPosts is not implemented (not served — ADR 0025 A-1)',
        platform: 'linkedin',
        details: { method: 'fetchRecentPosts' },
      })
    }
    return this.fetchRecentPostsBody(input)
  }

  // UNVERIFIED against the live API — ADR 0025 A-1. Re-verify when
  // r_member_social is approved. No test covers this body.
  //
  // Written against LinkedIn's documented Posts API "author finder"
  // (Microsoft Learn, the same LINKEDIN_POSTS_URL publish() already uses):
  // GET /rest/posts?author={URN}&q=author&count={pageSize}&start={offset},
  // original shares only (reshared posts are dropped — a reshareContext
  // field's presence marks a repost of someone else's content, ADR §2.4's
  // "original authored post" filter applied the same way TwitterProvider
  // applies exclude=replies,retweets), metrics: null always (fetchPostMetrics
  // still throws NOT_IMPLEMENTED — Amendment B §B.5, untouched here).
  private async fetchRecentPostsBody(input: FetchRecentPostsInput): Promise<RecentPostsPage> {
    const offset = input.cursor === null ? 0 : this.decodeReadCursor(input.cursor, input.socialAccountId)

    return withFreshToken(
      input.socialAccountId,
      (id) => this.refreshAccessToken({ socialAccountId: id }),
      async (token) => {
        const { createServiceRoleClient } = await import('@/lib/supabase/service')
        const client = createServiceRoleClient()
        const { data: account, error } = await client
          .from('social_accounts')
          .select('platform_user_id')
          .eq('id', input.socialAccountId)
          .single()

        if (error || !account) {
          throw new SocialProviderError({
            code: 'TOKEN_REVOKED',
            message: `fetchRecentPosts: social account ${input.socialAccountId} not found`,
            platform: 'linkedin',
          })
        }

        const authorUrn = account.platform_user_id as string
        const params = new URLSearchParams({
          author: authorUrn,
          q: 'author',
          count: String(input.pageSize),
          start: String(offset),
        })

        let resp: Response
        try {
          resp = await fetch(`${LINKEDIN_POSTS_URL}?${params}`, {
            headers: {
              Authorization: `Bearer ${token}`,
              'Linkedin-Version': LINKEDIN_VERSION,
              'X-Restli-Protocol-Version': '2.0.0',
            },
            signal: AbortSignal.timeout(SOCIAL_READ_TIMEOUT_MS),
          })
        } catch {
          throw new SocialProviderError({ code: 'NETWORK', message: 'fetchRecentPosts: network error', platform: 'linkedin' })
        }

        if (!resp.ok) {
          if (resp.status === 429) {
            const retryAfter = Number(resp.headers.get('Retry-After') ?? '60')
            throw new SocialProviderError({
              code: 'RATE_LIMITED',
              message: 'fetchRecentPosts: rate limited by LinkedIn',
              platform: 'linkedin',
              retryAfterSeconds: finiteRetryAfterSeconds(retryAfter),
            })
          }
          throw new SocialProviderError({
            code: mapHttpStatusToErrorCode(resp.status),
            message: `fetchRecentPosts: LinkedIn returned ${resp.status}`,
            platform: 'linkedin',
          })
        }

        const rawBody = await resp.json()
        let parsed: z.infer<typeof LinkedInPostsListSchema>
        try {
          parsed = LinkedInPostsListSchema.parse(rawBody)
        } catch (e) {
          throw new SocialProviderError({
            code: 'UNKNOWN',
            message: 'fetchRecentPosts: LinkedIn returned an unexpected posts response shape',
            platform: 'linkedin',
            details: { zodError: e instanceof Error ? e.message : String(e) },
          })
        }

        const posts: RecentPost[] = []
        for (const element of parsed.elements ?? []) {
          if (element.reshareContext) continue // original shares only

          const publishedDate = new Date(element.createdAt)
          if (!Number.isFinite(publishedDate.getTime())) {
            throw new SocialProviderError({ code: 'UNKNOWN', message: 'fetchRecentPosts: LinkedIn returned a non-finite createdAt', platform: 'linkedin' })
          }

          const rawContent = element.commentary ?? ''
          posts.push({
            platformPostId: element.id,
            publishedAt: formatISO(publishedDate),
            content: rawContent.length > RECENT_POST_CONTENT_MAX_CHARS ? rawContent.slice(0, RECENT_POST_CONTENT_MAX_CHARS) : rawContent,
            url: `https://www.linkedin.com/feed/update/${element.id}/`,
            format: element.content?.media ? 'image' : element.content?.article ? 'link' : 'text',
            metrics: null, // A-3 — metrics are a separate fetch, never included in this read for LinkedIn
          })
        }

        const total = parsed.paging?.total ?? posts.length
        const nextOffset = offset + posts.length
        const nextCursor = nextOffset < total ? this.encodeReadCursor(input.socialAccountId, nextOffset) : null
        return { posts, nextCursor }
      },
    )
  }

  private encodeReadCursor(socialAccountId: string, offset: number): string {
    return Buffer.from(JSON.stringify({ sa: socialAccountId, o: offset })).toString('base64url')
  }

  private decodeReadCursor(cursor: string, expectedAccountId: string): number {
    let parsed: unknown
    try {
      parsed = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8'))
    } catch {
      throw new SocialProviderError({ code: 'PLATFORM_REJECTED', message: 'fetchRecentPosts: cursor is unparseable', platform: 'linkedin', details: { reason: 'cursor_invalid' } })
    }
    const obj = parsed as { sa?: unknown; o?: unknown }
    if (typeof obj.sa !== 'string' || typeof obj.o !== 'number' || obj.sa !== expectedAccountId) {
      throw new SocialProviderError({ code: 'PLATFORM_REJECTED', message: 'fetchRecentPosts: cursor was not minted for this account', platform: 'linkedin', details: { reason: 'cursor_invalid' } })
    }
    return obj.o
  }
}
