import { formatISO } from 'date-fns'
import type {
  SocialProvider,
  OAuthAuthorizeInput,
  ExchangeCodeInput,
  TokenSet,
  PublishInput,
  PublishResult,
  FetchMetricsInput,
  PostMetrics,
  FetchEngagementInput,
  EngagementItem,
  RefreshAccessTokenInput,
  RevokeAccessTokenInput,
} from './types'
import { SocialProviderError } from './errors'
import { readRefreshToken, withFreshToken } from './vault'

export interface PostizConfig {
  baseUrl: string
  apiKey: string
}

export class PostizProvider implements SocialProvider {
  readonly platform = 'multi' as const
  private readonly baseUrl: string
  private readonly apiKey: string

  constructor({ baseUrl, apiKey }: PostizConfig) {
    if (!baseUrl || !apiKey) {
      throw new SocialProviderError({
        code: 'PROVIDER_NOT_CONFIGURED',
        message: 'PostizProvider requires baseUrl and apiKey',
      })
    }
    try {
      new URL(baseUrl)
    } catch {
      throw new SocialProviderError({
        code: 'PROVIDER_NOT_CONFIGURED',
        message: `PostizProvider: baseUrl is not a valid URL: ${baseUrl}`,
      })
    }
    this.baseUrl = baseUrl.replace(/\/$/, '')
    this.apiKey = apiKey
  }

  // Synchronous URL builder — no I/O. The state param is a pre-signed JWT
  // generated by the calling Server Action via signOAuthState().
  getOAuthAuthorizeUrl(input: OAuthAuthorizeInput): string {
    const params = new URLSearchParams({
      redirect_uri: input.redirectUri,
      scope: input.scopes.join(' '),
      state: input.state,
    })
    return `${this.baseUrl}/integrations/${input.platform}/authorize?${params}`
  }

  async exchangeOAuthCode(input: ExchangeCodeInput): Promise<TokenSet> {
    let resp: Response
    try {
      resp = await fetch(`${this.baseUrl}/integrations/${input.platform}/callback`, {
        method: 'POST',
        headers: this.authHeaders(),
        body: JSON.stringify({ code: input.code, redirectUri: input.redirectUri }),
      })
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'exchangeOAuthCode: network error',
        platform: input.platform,
        details: { cause: String(err) },
      })
    }

    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `exchangeOAuthCode: Postiz returned ${resp.status}`,
        platform: input.platform,
        details: { platform_message: body },
      })
    }

    const body = await resp.json()
    return this.normalizeTokenSet(body)
  }

  async publish(input: PublishInput): Promise<PublishResult> {
    return withFreshToken(
      input.socialAccountId,
      (id) => this.refreshAccessToken({ socialAccountId: id }),
      async (_token) => {
        const { createServiceRoleClient } = await import('@/lib/supabase/service')
        const client = createServiceRoleClient()
        const { data: account, error } = await client
          .from('social_accounts')
          .select('platform_user_id, platform')
          .eq('id', input.socialAccountId)
          .single()

        if (error || !account) {
          throw new SocialProviderError({
            code: 'TOKEN_REVOKED',
            message: `publish: social account ${input.socialAccountId} not found`,
          })
        }

        let resp: Response
        try {
          resp = await fetch(`${this.baseUrl}/posts`, {
            method: 'POST',
            headers: this.authHeaders(),
            body: JSON.stringify({
              content: input.content,
              tags: input.hashtags,
              media: input.mediaUrls.map((url) => ({ url })),
              providers: [{ id: account.platform_user_id }],
            }),
          })
        } catch (err) {
          throw new SocialProviderError({
            code: 'NETWORK',
            message: 'publish: network error',
            details: { cause: String(err) },
          })
        }

        return this.handlePublishResponse(resp)
      },
    )
  }

  async fetchPostMetrics(_input: FetchMetricsInput): Promise<PostMetrics | null> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'PostizProvider.fetchPostMetrics is not implemented in Phase 1',
      details: { method: 'fetchPostMetrics' },
    })
  }

  async fetchEngagement(_input: FetchEngagementInput): Promise<EngagementItem[]> {
    throw new SocialProviderError({
      code: 'NOT_IMPLEMENTED',
      message: 'PostizProvider.fetchEngagement is not implemented in Phase 1',
      details: { method: 'fetchEngagement' },
    })
  }

  async refreshAccessToken(input: RefreshAccessTokenInput): Promise<TokenSet> {
    const { createServiceRoleClient } = await import('@/lib/supabase/service')
    const client = createServiceRoleClient()

    const { data: account, error: accountError } = await client
      .from('social_accounts')
      .select('platform, vault_access_token_id, vault_refresh_token_id')
      .eq('id', input.socialAccountId)
      .single()

    if (accountError || !account) {
      throw new SocialProviderError({
        code: 'TOKEN_REVOKED',
        message: `refreshAccessToken: social account ${input.socialAccountId} not found`,
      })
    }

    const { token: refreshToken } = await readRefreshToken(input.socialAccountId)

    let resp: Response
    try {
      resp = await fetch(
        `${this.baseUrl}/integrations/${account.platform}/refresh`,
        {
          method: 'POST',
          headers: this.authHeaders(),
          body: JSON.stringify({ refreshToken }),
        },
      )
    } catch (err) {
      throw new SocialProviderError({
        code: 'NETWORK',
        message: 'refreshAccessToken: network error',
        details: { cause: String(err) },
      })
    }

    if (resp.status === 401 || resp.status === 403) {
      throw new SocialProviderError({
        code: 'TOKEN_REVOKED',
        message: 'refreshAccessToken: platform rejected the refresh token',
      })
    }

    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: 'PLATFORM_REJECTED',
        message: `refreshAccessToken: Postiz returned ${resp.status}`,
        details: { platform_message: body },
      })
    }

    const body = await resp.json()
    const newAccessToken: string = body.accessToken ?? body.access_token
    const newRefreshToken: string | null = body.refreshToken ?? body.refresh_token ?? null
    const expiresIn: number | null = body.expiresIn ?? body.expires_in ?? null
    const newExpiry = expiresIn ? formatISO(new Date(Date.now() + expiresIn * 1000)) : null

    // Update vault access token in-place
    await client.rpc('vault.update_secret', {
      secret_id: account.vault_access_token_id,
      new_secret: newAccessToken,
    })

    // If platform rotates the refresh token, update it too
    if (newRefreshToken && account.vault_refresh_token_id) {
      await client.rpc('vault.update_secret', {
        secret_id: account.vault_refresh_token_id,
        new_secret: newRefreshToken,
      })
    }

    // Bump token_expires_at
    await client
      .from('social_accounts')
      .update({ token_expires_at: newExpiry, updated_at: formatISO(new Date()) })
      .eq('id', input.socialAccountId)

    return {
      accessToken: newAccessToken,
      refreshToken: newRefreshToken,
      tokenExpiresAt: newExpiry,
      scopesGranted: body.scopesGranted ?? body.scopes ?? [],
    }
  }

  async revokeAccessToken(input: RevokeAccessTokenInput): Promise<void> {
    const { createServiceRoleClient } = await import('@/lib/supabase/service')
    const client = createServiceRoleClient()

    const { data: account } = await client
      .from('social_accounts')
      .select('platform, vault_access_token_id')
      .eq('id', input.socialAccountId)
      .single()

    if (!account?.vault_access_token_id) return

    const { data: token } = await client.rpc('get_vault_secret', {
      secret_id: account.vault_access_token_id,
    })

    if (!token) return

    try {
      await fetch(`${this.baseUrl}/integrations/${account.platform}/revoke`, {
        method: 'POST',
        headers: this.authHeaders(),
        body: JSON.stringify({ accessToken: token }),
      })
    } catch {
      // Best-effort: network failure on revoke is logged and discarded.
      // Caller still runs local cleanup via deactivateSocialAccount.
    }
  }

  // ---- private helpers ----

  private authHeaders(): Record<string, string> {
    return {
      Authorization: `Bearer ${this.apiKey}`,
      'Content-Type': 'application/json',
    }
  }

  private async handlePublishResponse(resp: Response): Promise<PublishResult> {
    if (resp.status === 429) {
      const retryAfter = Number(resp.headers.get('Retry-After') ?? '60')
      throw new SocialProviderError({
        code: 'RATE_LIMITED',
        message: 'publish: rate limited by Postiz',
        retryAfterSeconds: Number.isFinite(retryAfter) ? retryAfter : 60,
      })
    }

    if (resp.status === 401 || resp.status === 403) {
      throw new SocialProviderError({
        code: 'TOKEN_EXPIRED',
        message: `publish: Postiz returned ${resp.status}`,
      })
    }

    if (!resp.ok) {
      const body = await resp.json().catch(() => ({}))
      throw new SocialProviderError({
        code: resp.status >= 500 ? 'NETWORK' : 'PLATFORM_REJECTED',
        message: `publish: Postiz returned ${resp.status}`,
        details: { platform_message: body },
      })
    }

    const body = await resp.json()
    // Postiz returns per-provider results; we extract the first one.
    const result = Array.isArray(body.providers) ? body.providers[0] : body
    return {
      platformPostId: result.platformPostId ?? result.id ?? String(body.id),
      publishedAt: result.publishedAt ?? formatISO(new Date()),
      url: result.url ?? null,
    }
  }

  private normalizeTokenSet(body: Record<string, unknown>): TokenSet {
    return {
      accessToken: (body['accessToken'] ?? body['access_token']) as string,
      refreshToken: (body['refreshToken'] ?? body['refresh_token'] ?? null) as string | null,
      tokenExpiresAt: body['expiresIn']
        ? formatISO(new Date(Date.now() + Number(body['expiresIn']) * 1000))
        : null,
      scopesGranted: ((body['scopesGranted'] ?? body['scopes'] ?? []) as string[]),
      platformUserId: body['integrationId'] as string | undefined,
      platformUsername: (body['username'] ?? body['handle']) as string | undefined,
      platformDisplayName: (body['displayName'] ?? body['name'] ?? null) as string | null,
    }
  }
}
